monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      handler: nested
      excluded_http_codes: [404, 405]
      buffer_size: 50 # How many messages should be saved? Prevent memory leaks
      formatter: monolog.formatter.session_request
    nested:
      type: stream
      path: php://stderr
      level: debug
      formatter: monolog.formatter.json
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine"]
      formatter: monolog.formatter.session_request
    file_log:
      type: rotating_file
      path: "%kernel.logs_dir%/log-%kernel.environment%.log"
      level: debug
      formatter: monolog.formatter.session_request
    syslog_handler:
      type: syslog
      level: error
