# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false
    bind:
      Psr\Log\LoggerInterface: '@monolog.logger.request'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'
      - '../src/Tests/'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  exception_handler.listener:
    class: App\Application\Handlers\ExceptionHandler
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
    arguments:
      - '%env(APP_ENV)%'
      - '%kernel.debug%'
  App\Application\Actions\:
    public: true
    resource: '../src/Application/Actions/*'
    tags:
      - controller.service_arguments
    exclude:
      - '../src/Application/Actions/Action.php'
      - '../src/Application/Actions/ActionError.php'
      - '../src/Application/Actions/ActionPayload.php'
  monolog.formatter.session_request:
    class: Monolog\Formatter\LineFormatter
    arguments:
      - "[%%datetime%%] %%channel%%.%%level_name%%: %%message%% %%extra%%\n"
  App\Application\Processors\SessionRequestProcessor:
    tags:
      - { name: monolog.processor }
